# name: Jeykll CI

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/cache@v1
#         with:
#           path: vendor/bundle
#           key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-gems-
#       - name: Set up Ruby 2.6
#         uses: actions/setup-ruby@v1
#         with:
#           ruby-version: 2.6.x
#       - name: 'Update Rubygems'
#         run: 'gem update --system --no-document'
#       - name: 'Update Bundler'
#         run: 'gem update bundler --no-document'
#       - name: 'Set up bundle'
#         run: |
#           bundle config path vendor/bundle
#           bundle install --jobs 4 --retry 3
#       - name: 'Build site'
#         run: 'bundle exec jekyll build'
#         env:
#           JEKYLL_ENV: production
#       - name: 'Deploy to GitHub Pages'
#         uses: JamesIves/github-pages-deploy-action@3.4.8
#         with:
#           ACCESS_TOKEN: ${{ github.token }}
#           BRANCH: gh-pages # The branch the action should deploy to.
#           FOLDER: _site # The folder the action should deploy.
